### ISSUE TITLE
Can't use in svelte-kit with multiple __layouts

### ISSUE THREAD

**Issue by SorenHolstHansen** [haruaki07/phosphor-svelte#2]
I have the following structure in the routes folder
```
routes/
- __layout.svelte
- index.svelte
- login/
  - __layout.reset.svelte
  - index.svelte
```

And when i use an icon in both of the index.svelte files it throws the following error.

```
Error when evaluating SSR module /Users/.../src/routes/login/index.svelte:
/Users/.../node_modules/phosphor-svelte/lib/index.js:1
export { default as IconContext } from './IconContext';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (/Users/.../node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:73417:17)
    at ssrImport (/Users/.../node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:73369:20)
Unexpected token 'export'
```

**Comment by haruaki07** [comment]
I've tried to reproduce your problems, but I don't have any problems.

Can you provide a repository that can trigger this error? thanks!

**Comment by SorenHolstHansen** [comment]
It must be something with my other setup then, I couldn't reproduce with a clean sveltekit either
