### ISSUE TITLE
sveltePhosphorOptimize fails in SvelteKit app with Tailwind CSS

### ISSUE THREAD

**Issue by story75** [haruaki07/phosphor-svelte#28]
First off, thanks for the project. 

I've upgraded a private SvelteKit application with Tailwind CSS, which was using v2 of your lib previously. After upgrading to v3 and changing the pre-processor the build fails directly at the start with a cryptic "runnerError: Error: RunnerError" and "Error [RollupError]: Expression expected" originating from "vite-plugin-svelte-phosphor-optimize".

The issue is that unlike v2, which only operated on .svelte files, v3 operates on all files except for children of ["/node_modules/", "/.svelte-kit/", "virtual:__sveltekit"](https://github.com/haruaki07/phosphor-svelte/blob/main/vite/index.js#L13C10-L13C66).

The culprit here is that Vite processes the app.css file and tries to call [let root = this.parse(code);](https://github.com/haruaki07/phosphor-svelte/blob/main/vite/index.js#L20C7-L20C35) on a css file.

Locally I solved this by adding ".css" to the exceptions to restore the app, but this may not be feasible for a general fix here, depending on the goal of the preprocessor. It might make sense to rather force it to only operate on .svelte, .js and .ts files instead.

So the shortest form to reproduce the issue is to create a clean SvelteKit app with Tailwind CSS, add the npm dependency in v3 and add the sveltePhosphorOptimize Vite plugin.

**Comment by haruaki07** [comment]
I couldn't reproduce this, can you please create a minimal reproduction repository?

**Comment by story75** [comment]
You can see it here: https://github.com/story75/phospor-repro
Used bun, but it also happens with npm

So steps were:
- create a new repo
- bunx sv create (demo template, typescript, tailwindcss)
- add phosphor-svelte@3.0.0
- update vite config
- run bun dev
- open http://localhost:5173 in your browser
- observe the terminal

```
> phospor-repro@0.0.1 dev
> vite dev


  VITE v6.0.3  ready in 3296 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
10:18:35 PM [vite] (ssr) Error when evaluating SSR module /src/routes/+page.svelte:
|- RollupError: Expression expected
    at getRollupError (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at convertProgram (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:1084:26)
    at parseAst (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:2069:87)
    at TransformPluginContext.parse (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47073:12)
    at TransformPluginContext.transform (file://<redacted>phospor-repro/node_modules/phosphor-svelte/vite/index.js:20:23)
    at EnvironmentPluginContainer.transform (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47002:19)
    at async loadAndTransform (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40852:27)

Error [RollupError]: Expression expected
    at getRollupError (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at convertProgram (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:1084:26)
    at parseAst (file://<redacted>phospor-repro/node_modules/rollup/dist/es/shared/parseAst.js:2069:87)
    at TransformPluginContext.parse (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47073:12)
    at TransformPluginContext.transform (file://<redacted>phospor-repro/node_modules/phosphor-svelte/vite/index.js:20:23)
    at EnvironmentPluginContainer.transform (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47002:19)
    at async loadAndTransform (file://<redacted>phospor-repro/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40852:27) {
  code: 'PARSE_ERROR',
  pos: 2,
  plugin: 'vite-plugin-svelte-phosphor-optimize',
  id: '<redacted>phospor-repro/src/routes/Counter.svelte?svelte&type=style&lang.css',
  pluginCode: '\n' +
    '\t.counter.s-HTE2L0KcXC-T {\n' +
    '\t\tdisplay: flex;\n' +
    '\t\tborder-top: 1px solid rgba(0, 0, 0, 0.1);\n' +
    '\t\tborder-bottom: 1px solid rgba(0, 0, 0, 0.1);\n' +
    '\t\tmargin: 1rem 0;\n' +
    '\t}\n' +
    '\n' +
    '\t.counter.s-HTE2L0KcXC-T button:where(.s-HTE2L0KcXC-T) {\n' +
    '\t\twidth: 2em;\n' +
```
